### ISSUE TITLE
fish: Unknown command nvm

### ISSUE THREAD

**Issue by faizaldong** [ghaiklor/iterm-fish-fisher-osx#10] opened 2019-11-05 07:48 UTC
Hi @ghaiklor 

Is your software support for NVM?
I installed **nvm**  from this repo https://github.com/nvm-sh/nvm. I had been using nvm for quite some time. after use your software, I cant run any **nvm** command

<img width="682" alt="Screenshot 2019-11-05 at 3 47 42 PM" src="https://user-images.githubusercontent.com/17352624/68188218-a442a180-ffe3-11e9-810f-fc641fb21a55.png">

**Comment by ghaiklor** [comment] 2019-11-05 18:23
Hey @faizaldong 

All my script does is install Fish Shell with plugins and configures iTerm for custom fonts and color scheme.

It can not update your environment configuration in any way, literally. So, it means:

1) You did not finish nvm installation
2) Or, maybe, nvm is not available in $PATH

**Comment by ghaiklor** [comment] 2019-11-05 18:25
https://github.com/nvm-sh/nvm#important-notes

Read notes how to fix that for Fish shell on nvm page

![IMG_0085](https://user-images.githubusercontent.com/3625244/68234703-745ac480-000a-11ea-8dc4-6fe719e3e3cf.jpeg)

**Comment by ghaiklor** [comment] 2019-11-05 18:27
Closing as it is not related to this project. The issue is with Fish Shell and that nvm does not support it.

**Closed as completed by ghaiklor** 2019-11-05 18:27 UTC

**Comment by ghaiklor** [comment] 2019-11-05 18:30
BTW @faizaldong I’m using fisherman under the hood, so the best choice for you to resolve the issue is to choose fnm - fisherman-based version manager - https://github.com/jorgebucaran/fish-nvm

**Comment by faizaldong** [comment] 2019-11-07 03:51
> BTW @faizaldong I’m using fisherman under the hood, so the best choice for you to resolve the issue is to choose fnm - fisherman-based version manager - https://github.com/jorgebucaran/fish-nvm

Hi thank you for the suggestion! It solved the issue
