### ISSUE TITLE
math: Error: Too many arguments

### ISSUE THREAD

**Issue by DanielSchreurs** [ghaiklor/iterm-fish-fisher-osx#6] opened 2019-03-30 11:21 UTC
Thank you for this nice script which is really useful. When start iTerm I have this message: 

```
Last login: Sat Mar 30 11:00:31 on ttys003
math: Error: Too many arguments
'96,2 / 10'
```

Can you tell me where I can replace the `,` by `.` to avoid this message at starting? 

Item2 : Build 3.2.8
MacOS Mojave : 10.14.3

**Comment by ghaiklor** [comment] 2019-03-30 15:23
Hi @DanielSchreurs 

iTerm2: Build 3.2.8
MacOS Mojave: 10.14.4
Fish Shell: 3.0.2

The issue is not reproducing from my side.

1) Provide Fish Shell version `fish --version`;
2) Have you modified any of fish configuration?
3) Maybe an issue with some of fisher plugins, try to update fisher and its plugins by `fisher self-update && fisher`;

**Comment by DanielSchreurs** [comment] 2019-04-02 10:02
I'm on `fish, version 3.0.2`

I definitely think that there is a problem with `math`. How can I fix it ? 

Output from `fisher self-update && fisher` 
```
fisher self-update && fisher                   Mar  2 avr 11:55:34 2019
fetching https://raw.githubusercontent.com/jorgebucaran/fisher/master/fisher.fish
fisher is already up-to-date
To completely erase z's data, remove:
/Users/danielschreurs/.local/share/z/data
fetching https://codeload.github.com/igalic/anicode/tar.gz/master
fetching https://codeload.github.com/edc/bass/tar.gz/master
fetching https://codeload.github.com/oh-my-fish/plugin-battery/tar.gz/master
fetching https://codeload.github.com/oh-my-fish/theme-bobthefish/tar.gz/master
fetching https://codeload.github.com/laughedelic/brew-completions/tar.gz/master
fetching https://codeload.github.com/franciscolourenco/done/tar.gz/master
fetching https://codeload.github.com/Shadowigor/plugin-errno-grep/tar.gz/master
fetching https://codeload.github.com/gyakovlev/fish-fzy/tar.gz/master
fetching https://codeload.github.com/oh-my-fish/plugin-grc/tar.gz/master
fetching https://codeload.github.com/oh-my-fish/plugin-license/tar.gz/master
fetching https://codeload.github.com/oh-my-fish/plugin-node-binpath/tar.gz/master
fetching https://codeload.github.com/oh-my-fish/plugin-pj/tar.gz/master
fetching https://codeload.github.com/fisherman/shark/tar.gz/master
fetching https://codeload.github.com/Markcial/upto/tar.gz/master
fetching https://codeload.github.com/jethrokuan/z/tar.gz/master
linking ~/.config/fish/functions/anicode.fish
linking ~/.config/fish/functions/__bass.py
linking ~/.config/fish/functions/bass.fish
linking ~/.config/fish/functions/battery.fish
linking ~/.config/fish/functions/battery.info.update.darwin.fish
linking ~/.config/fish/functions/battery.info.update.fish
linking ~/.config/fish/functions/battery.info.update.linux.fish
linking ~/.config/fish/conf.d/plugin-battery_init.fish
math: Error: Too many arguments
'100,0 / 10'
    ^
linking ~/.config/fish/functions/__bobthefish_colors.fish
linking ~/.config/fish/functions/__bobthefish_display_colors.fish
linking ~/.config/fish/functions/__bobthefish_glyphs.fish
linking ~/.config/fish/functions/bobthefish_display_colors.fish
linking ~/.config/fish/functions/fish_greeting.fish
linking ~/.config/fish/functions/fish_mode_prompt.fish
linking ~/.config/fish/functions/fish_prompt.fish
linking ~/.config/fish/functions/fish_right_prompt.fish
linking ~/.config/fish/functions/fish_title.fish
linking ~/.config/fish/completions/brew.fish
linking ~/.config/fish/conf.d/done.fish
linking ~/.config/fish/functions/errno-grep.fish
linking ~/.config/fish/completions/errno-grep.fish
linking ~/.config/fish/functions/fkill.fish
linking ~/.config/fish/functions/fzy_select_directory.fish
linking ~/.config/fish/functions/fzy_select_history.fish
linking ~/.config/fish/conf.d/fish-fzy_key_bindings.fish
linking ~/.config/fish/functions/grc.wrap.fish
linking ~/.config/fish/conf.d/plugin-grc_init.fish
linking ~/.config/fish/functions/license.fish
linking ~/.config/fish/completions/license.fish
linking ~/.config/fish/conf.d/plugin-node-binpath_init.fish
linking ~/.config/fish/functions/pj.fish
linking ~/.config/fish/completions/pj.fish
linking ~/.config/fish/functions/spark.fish
linking ~/.config/fish/functions/upto.fish
linking ~/.config/fish/completions/upto.fish
linking ~/.config/fish/functions/__z.fish
linking ~/.config/fish/functions/__z_add.fish
linking ~/.config/fish/functions/__z_clean.fish
linking ~/.config/fish/functions/__z_complete.fish
linking ~/.config/fish/conf.d/z.fish
math: Error: Too many arguments
'100,0 / 10'
    ^
math: Error: Too many arguments
'100,0 / 10'
    ^
math: Error: Too many arguments
'100,0 / 10'
    ^
fetching https://codeload.github.com/fishpkg/fish-spin/tar.gz/master
math: Error: Too many arguments
'100,0 / 10'
    ^
fetching https://codeload.github.com/fishpkg/fish-get/tar.gz/master
math: Error: Too many arguments
'100,0 / 10'
    ^
fetching https://codeload.github.com/markcial/choices/tar.gz/master
fetching https://codeload.github.com/jorgebucaran/fish-getopts/tar.gz/master
fetching https://codeload.github.com/fishpkg/fish-humanize-duration/tar.gz/master
linking ~/.config/fish/functions/spin.fish
linking ~/.config/fish/completions/spin.fish
linking ~/.config/fish/functions/get.fish
linking ~/.config/fish/completions/get.fish
linking ~/.config/fish/functions/choices.fish
linking ~/.config/fish/functions/getopts.fish
linking ~/.config/fish/functions/humanize_duration.fish
math: Error: Too many arguments
'100,0 / 10'
    ^
fetching https://codeload.github.com/fisherman/getopts/tar.gz/master
linking ~/.config/fish/functions/getopts.fish
added 1 package, updated 20 packages, removed 1 package in 3,37s

```

**Comment by ghaiklor** [comment] 2019-04-04 11:41
It is a very strange error. I can not reproduce it on my side.

I'd rather make an assumption that something is wrong on your host machine. At the moment I do not know how can I help you.

**Comment by ghaiklor** [comment] 2019-04-07 11:03
I had a clean setup after MacOS reinstall and used the script. No issues were addressed with the error. So closing for now as "cannot reproduce it".

In case you have more additional information that could help me with that - feel free to re-open it.

**Comment by behrtam** [comment] 2019-12-19 13:02
I now have the same `math: Error: Too many arguments` problem on a fresh macOS 10.13.6 setup with:
fish version 3.0.2
fisher version 3.2.10

**Comment by ghaiklor** [comment] 2019-12-20 10:56
@behrtam 

Assumption: the error originates from battery plugin - https://github.com/faho/pkg-battery/blob/master/battery.fish#L72 Can you uninstall the battery plugin via fisher and check if error still reproduces or not?

**Comment by ghaiklor** [comment] 2020-01-19 16:12
This issue became stale, closing

**Closed as completed by ghaiklor** 2020-01-19 16:12 UTC

**Comment by adavidzh** [comment] 2024-09-01 10:00
I just hit this and confirm that it is the battery plugin since in my system:
```console
$ echo $BATTERY_PCT
69,0
```

Traced the code where `BATTERY_PCT` is computed to [this line](https://github.com/faho/pkg-battery/blob/c11f9c049c28471f1794239bb72df7a116746045/battery.fish#L62-L63) and in my system there seems to be no comma:
```console
$ echo "$BATTERY_CUR_CAP / $BATTERY_MAX_CAP * 100" | bc -l
69.00000000000000000000
```

FWIW, as concerns `bc` in my system:
```console
$ which bc
/usr/bin/bc
$ bc -V
bc 6.5.0
Copyright (c) 2018-2023 Gavin D. Howard and contributors
Report bugs at: https://git.gavinhoward.com/gavin/bc

This is free software with ABSOLUTELY NO WARRANTY.
```

I wonder if this behaviour may be related to [this](https://github.com/fish-shell/fish-shell/issues/5421) locale-related issue. In my system `LC_NUMERIC` is not set and:
```console
$ echo $LC_ALL
en_US.UTF-8
```

**Comment by ghaiklor** [comment] 2024-09-12 14:13
@adavidzh nice catch, thanks for the follow-up and writing it here!

**Comment by adavidzh** [comment] 2024-09-12 14:48
Sure thing. Anything I can do to debug this and help get this fixed?

**Comment by ghaiklor** [comment] 2024-09-23 18:13
@adavidzh nope, it turned out that the actual benefit of a battery plugin does not cost the issues it brings, so I've removed it from the installer 😄
